PortalAcademico/AcademicGate.Web/Controllers/RegisterController.cs
using AcademicGate.Web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AcademicGate.Web.Controllers
{
    public class RegisterController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private readonly ApplicationDbContext _context;

        public RegisterController()
        {
            _context = new ApplicationDbContext();
        }

        public RegisterController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        [AllowAnonymous]
        public ActionResult RegisterUser()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RegisterUser(RegisterViewModel model, string permission)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    Name = model.Name,
                    Cpf = model.Cpf,
                    PhoneNumber = model.Phone,
                    BirthDate = model.BirthDate,
                    IngressedYear = DateTime.Now,
                    Address = model.Address,
                    Permission = permission,
                    UserName = model.Email,
                    Email = model.Email
                };

                var result = await UserManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                    return RedirectToAction("Index", "Home");

                AddErrors(result);
            }

            // Se chegamos até aqui e houver alguma falha, exiba novamente o formulário
            return View(model);
        }

        

        [AllowAnonymous]
        public ActionResult RegisterTeacher()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RegisterTeacher(RegisterViewModel model, string permission)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    Name = model.Name,
                    Cpf = model.Cpf,
                    PhoneNumber = model.Phone,
                    BirthDate = model.BirthDate,
                    Address = model.Address,
                    Formation = model.Formation,
                    Permission = permission,
                    UserName = model.Email,
                    Email = model.Email,
                   IngressedYear = DateTime.Now
                };

                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }

                AddErrors(result);
            }

            // Se chegamos até aqui e houver alguma falha, exiba novamente o formulário
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult RegisterStudent()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RegisterStudent(RegisterViewModel model, string serie)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    Name = model.Name,
                    MotherName = model.MotherName,
                    IngressedYear = DateTime.Now,
                    IngressedSerie = serie,
                    Cpf = model.Cpf,
                    RA = model.RA,
                    Permission = "Aluno",
                    PhoneNumber = model.Phone,
                    UserName = model.Email,
                    BirthDate = model.BirthDate,
                    Address = model.Address,
                    Email = model.Email
                };

                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // Se chegamos até aqui e houver alguma falha, exiba novamente o formulário
            return View(model);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult RegisterCalendar()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult RegisterCalendar(AcademicCalendar model)
        {
            _context.AcademicCalendars.Add(model);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult RegisterTeam()
        {

            ViewBag.DisciplineId = new SelectList(_context.Disciplines, "Id", "Name");
            ViewBag.UserId = new SelectList(_context.Users.Where(u => u.Permission == "Professor"), "Id", "Name");
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult RegisterTeam(Team model)
        {
            model.Discipline = _context.Disciplines.Find(model.DisciplineId);

            model.Name = model.Discipline.Name + " - sala " + model.Room;
            _context.Teams.Add(model);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult RegisterDicipline()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult RegisterDicipline(Discipline model)
        {
            _context.Disciplines.Add(model);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult RegisterNote()
        {

            ViewBag.TeamId = new SelectList(_context.Teams, "Id", "Name");
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult RegisterNote(NotesStudentTeamViewModel model, string typeNote, double valueNote)
        {

            var aluno = _context.Users.FirstOrDefault(u => u.Name == model.StudentName);

            var notes = _context
                .RegistrationStudentTeams
                .FirstOrDefault(n => n.StudentId == aluno.Id && n.TeamId == model.TeamId);

            if (typeNote == "AP1")
            {
                if (notes.AP1 != 0)
                {
                    ViewBag.TeamId = new SelectList(_context.Teams, "Id", "Name");
                    ViewBag.Message = "AP1 já foi lançada nessa turma";
                    return View();
                }
                else
                    model.AP1 = valueNote;
            }

            if (typeNote == "AP2")
            {
                if (notes.AP2 != 0)
                {
                    ViewBag.Message = "AP2 já foi lançada nessa turma";
                    return View();
                }
                model.AP2 = valueNote;
            }

            if (notes == null)
            {
                var notesStudentTeam = new RegistrationStudentTeam()
                {
                    StudentId = aluno.Id,
                    TeamId = model.TeamId,
                    AP1 = model.AP1,
                    AP2 = model.AP2
                };

                _context.RegistrationStudentTeams.Add(notesStudentTeam);
            }
            else
            {
                notes.AP1 = (notes.AP1 > 0) ? notes.AP1 : model.AP1;
                notes.AP2 = (notes.AP2 > 0) ? notes.AP2 : model.AP2;
            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult RegisterStudentTeam()
        {

            ViewBag.TeamId = new SelectList(_context.Teams, "Id", "Name");
            return View();
        }

        public ActionResult RegisterStudentTeam(NotesStudentTeamViewModel model, string serie)
        {
            var aluno = _context.Users.FirstOrDefault(u => u.Name == model.StudentName);

            if (_context.RegistrationStudentTeams.Any(r => r.StudentId == aluno.Id && r.TeamId == model.TeamId))
            {
                ViewBag.TeamId = new SelectList(_context.Teams, "Id", "Name");
                ViewBag.Message = "Já exite matricula para esse aluno nessa turma";
                return View();
            }

            var registration = new RegistrationStudentTeam()
            {
                StudentId = aluno.Id,
                TeamId = model.TeamId,
                Serie = serie
            };
            _context.RegistrationStudentTeams.Add(registration);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]

PortalAcademico/AcademicGate.Web/Controllers/ReportController.cs
using AcademicGate.Web.Models;
using System.Linq;
using System.Web.Mvc;

namespace AcademicGate.Web.Controllers
{
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportController()
        {
            _context = new ApplicationDbContext();
        }
        

        [HttpGet]
        public ActionResult ListStudents()  
        {
            ViewBag.Students = _context.Users.Where(u=> u.Permission == "Aluno").Select(a=> a.Name).ToList();

            return View();
        }

        [HttpGet]
        public ActionResult ListTeachers()
        {

            ViewBag.Teachers = _context.Users.Where(u => u.Permission == "Professor").Select(a => a.Name).ToList();
            return View();
        }

        [HttpGet]
        public ActionResult ListUsers()
        {
            ViewBag.Users = _context.Users.Select(a => a.Name).ToList();
            return View();
        }

        [AllowAnonymous]
        public ActionResult ShowAvaliations()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult ShowReports()   
        {
            return View();
        }
    }
}

PortalAcademico/AcademicGate.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@model AcademicGate.Web.Models.ApplicationDbContext

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Portal Acadêmico</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @if (Request.IsAuthenticated)
        {
            var admin = User.IsInRole("Admin");
            var coord = User.IsInRole("Coordenador");
            var prof = User.IsInRole("Professor");
            var aluno = User.IsInRole("Aluno");

            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @*<li>@Html.ActionLink("Registrar-se", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>*@
                        <li class="dropdown" id="cadastro">
                            <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Cadastrar
                            </a>
                            <ul class="dropdown-menu">
                                @if (admin)
                                {
                                    <li>@Html.ActionLink("Administrador", "RegisterUser", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                    <li>@Html.ActionLink("Coordenador", "RegisterUser", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                }
                                @if (admin || prof)
                                {
                                    <li>@Html.ActionLink("Matricula", "RegisterStudentTeam", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                    <li>@Html.ActionLink("Professor", "RegisterTeacher", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                    <li>@Html.ActionLink("Aluno", "RegisterStudent", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                    <li>@Html.ActionLink("Calendario Acadêmico", "RegisterCalendar", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                    <li>@Html.ActionLink("Turmas", "RegisterTeam", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                    <li>@Html.ActionLink("Disciplinas", "RegisterDicipline", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                }
                                <li>@Html.ActionLink("Notas", "RegisterNote", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                            </ul>
                        </li>
                        <li class="dropdown" id="relatorios">
                            <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Relatorios
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Alunos", "ListStudents", "Report", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                <li>@Html.ActionLink("Professores", "ListTeachers", "Report", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                @if (admin)
                                {
                                    <li>@Html.ActionLink("Usuários", "ListUsers", "Report", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                }
                            </ul>
                        </li>
                        @if (admin || prof)
                        {
                            <li>@Html.ActionLink("Exibir Provas", "ShowAvaliations", "Report", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                            <li>@Html.ActionLink("Emitir Boletim", "ShowReports", "Report", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        }
                        @if (admin || prof)
                        {
                            <li class="dropdown" id="professor">
                                <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Professor
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Lançar notas", "RegisterNote", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                    <li>@Html.ActionLink("Lançar frequêcia", "GetTeamRegistred", "Register", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                    <li><a>Imprimir frequência</a></li>
                                    <li><a>Imprimir mapa de notas</a></li>
                                    <li><a>Submeter provas</a></li>
                                </ul>
                            </li>
                        }
                        @if (admin || aluno)
                        {
                            <li class="dropdown" id="aluno">
                                <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Aluno
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a>Emitir declaração</a></li>
                                    <li><a>Verificar situação</a></li>
                                    <li><a>Verificar conteúdo na turma</a></li>
                                    <li><a>Solicitar matricula</a></li>
                                    <li><a>Emitir atestado</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        }
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Portal Acadêmico</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>